import { CountyType, PlaceSuggestionType } from "@/src/libs/types";

export const ncPopularCounties: CountyType[] = [
  {
    id: "co-sf",
    name: "San Francisco County",
    places: [
      // --- AIRPORTS & FBOs ---
      {
        id: "sf-air-1",
        name: "San Francisco International Airport (SFO)",
        category: "airport",
        lat: 37.6213,
        lng: -122.379,
        address: "San Francisco, CA 94128",
      },
      {
        id: "sf-air-2",
        name: "Signature Aviation SFO (Private Jet FBO)",
        category: "airport",
        lat: 37.6285,
        lng: -122.3812,
        address: "1052 N Access Rd, San Francisco, CA 94128",
      },
      {
        id: "sf-air-3",
        name: "SFO International Terminal VIP Drop-off",
        category: "airport",
        lat: 37.6189,
        lng: -122.386,
        address: "International Terminal, San Francisco, CA 94128",
      },
      {
        id: "sf-air-4",
        name: "SFO Corporate Aviation Terminal",
        category: "airport",
        lat: 37.624,
        lng: -122.391,
        address: "624 S Airport Blvd, South San Francisco, CA 94080",
      },
      // --- HOTELS ---
      {
        id: "sf-htl-1",
        name: "The Fairmont San Francisco (Nob Hill)",
        category: "hotel",
        lat: 37.7925,
        lng: -122.4103,
        address: "950 Mason St, San Francisco, CA 94108",
      },
      {
        id: "sf-htl-2",
        name: "The Ritz-Carlton, San Francisco",
        category: "hotel",
        lat: 37.7918,
        lng: -122.4072,
        address: "600 Stockton St, San Francisco, CA 94108",
      },
      {
        id: "sf-htl-3",
        name: "The St. Regis San Francisco",
        category: "hotel",
        lat: 37.7858,
        lng: -122.4013,
        address: "125 3rd St, San Francisco, CA 94103",
      },
      {
        id: "sf-htl-4",
        name: "Four Seasons Hotel San Francisco at Embarcadero",
        category: "hotel",
        lat: 37.7932,
        lng: -122.4005,
        address: "222 Sansome St, San Francisco, CA 94104",
      },
      // --- SHOPPING ---
      {
        id: "sf-shp-1",
        name: "Union Square Luxury District",
        category: "shopping",
        lat: 37.7876,
        lng: -122.4066,
        address: "333 Post St, San Francisco, CA 94108",
      },
      {
        id: "sf-shp-2",
        name: "Westfield San Francisco Centre",
        category: "shopping",
        lat: 37.7841,
        lng: -122.4076,
        address: "865 Market St, San Francisco, CA 94103",
      },
      {
        id: "sf-shp-3",
        name: "Fillmore Street Shopping District",
        category: "shopping",
        lat: 37.7902,
        lng: -122.4346,
        address: "2000 Fillmore St, San Francisco, CA 94115",
      },
      {
        id: "sf-shp-4",
        name: "Ferry Building Marketplace",
        category: "shopping",
        lat: 37.7955,
        lng: -122.3933,
        address: "1 Ferry Building, San Francisco, CA 94111",
      },
      // --- UNIVERSITIES ---
      {
        id: "sf-uni-1",
        name: "University of San Francisco",
        category: "university",
        lat: 37.7766,
        lng: -122.4508,
        address: "2130 Fulton St, San Francisco, CA 94117",
      },
      {
        id: "sf-uni-2",
        name: "UC San Francisco (UCSF Parnassus Campus)",
        category: "university",
        lat: 37.7631,
        lng: -122.4578,
        address: "505 Parnassus Ave, San Francisco, CA 94143",
      },
      {
        id: "sf-uni-3",
        name: "San Francisco State University",
        category: "university",
        lat: 37.7241,
        lng: -122.4799,
        address: "1600 Holloway Ave, San Francisco, CA 94132",
      },
      {
        id: "sf-uni-4",
        name: "City College of San Francisco",
        category: "university",
        lat: 37.7262,
        lng: -122.4522,
        address: "50 Frida Kahlo Way, San Francisco, CA 94112",
      },
      // --- ATTRACTIONS (Chauffeur Hotspots) ---
      {
        id: "sf-att-1",
        name: "Golden Gate Bridge (Vista Point)",
        category: "attraction",
        lat: 37.8199,
        lng: -122.4783,
        address: "Golden Gate Bridge, San Francisco, CA 94129",
      },
      {
        id: "sf-att-2",
        name: "Palace of Fine Arts (Gala Venue)",
        category: "attraction",
        lat: 37.8029,
        lng: -122.4484,
        address: "3601 Lyon St, San Francisco, CA 94123",
      },
      {
        id: "sf-att-3",
        name: "Chase Center (VIP Suites & Concerts)",
        category: "attraction",
        lat: 37.768,
        lng: -122.3877,
        address: "1 Warriors Way, San Francisco, CA 94158",
      },
      {
        id: "sf-att-4",
        name: "Oracle Park (Lexus Field Club Entrance)",
        category: "attraction",
        lat: 37.7786,
        lng: -122.3893,
        address: "24 Willie Mays Plaza, San Francisco, CA 94107",
      },
      // --- BUSINESS ---
      {
        id: "sf-bus-1",
        name: "Salesforce Tower",
        category: "business",
        lat: 37.7897,
        lng: -122.3972,
        address: "415 Mission St, San Francisco, CA 94105",
      },
      {
        id: "sf-bus-2",
        name: "Uber Technologies HQ",
        category: "business",
        lat: 37.7688,
        lng: -122.3898,
        address: "1725 3rd St, San Francisco, CA 94158",
      },
      {
        id: "sf-bus-3",
        name: "Wells Fargo Corporate HQ",
        category: "business",
        lat: 37.7934,
        lng: -122.4027,
        address: "420 Montgomery St, San Francisco, CA 94104",
      },
      {
        id: "sf-bus-4",
        name: "OpenAI Headquarters",
        category: "business",
        lat: 37.7624,
        lng: -122.4148,
        address: "3180 18th St, San Francisco, CA 94110",
      },
    ],
  },
  {
    id: "co-santa-clara",
    name: "Santa Clara County",
    places: [
      // --- AIRPORTS & FBOs ---
      {
        id: "sc-air-1",
        name: "San Jose Mineta International Airport (SJC)",
        category: "airport",
        lat: 37.3639,
        lng: -121.9289,
        address: "1701 Airport Blvd, San Jose, CA 95110",
      },
      {
        id: "sc-air-2",
        name: "Atlantic Aviation SJC (Private Jet Center)",
        category: "airport",
        lat: 37.3682,
        lng: -121.932,
        address: "1250 Aviation Ave, San Jose, CA 95110",
      },
      {
        id: "sc-air-3",
        name: "Moffett Federal Airfield (Silicon Valley Executive Jets)",
        category: "airport",
        lat: 37.4161,
        lng: -122.0492,
        address: "Moffett Blvd, Mountain View, CA 94035",
      },
      {
        id: "sc-air-4",
        name: "Palo Alto Airport",
        category: "airport",
        lat: 37.4611,
        lng: -122.115,
        address: "1925 Embarcadero Rd, Palo Alto, CA 94303",
      },
      // --- HOTELS ---
      {
        id: "sc-htl-1",
        name: "Rosewood Sand Hill (Venture Capital Hub)",
        category: "hotel",
        lat: 37.4221,
        lng: -122.2016,
        address: "2825 Sand Hill Rd, Menlo Park, CA 94025",
      },
      {
        id: "sc-htl-2",
        name: "Signia by Hilton San Jose",
        category: "hotel",
        lat: 37.3323,
        lng: -121.8895,
        address: "170 S Market St, San Jose, CA 95113",
      },
      {
        id: "sc-htl-3",
        name: "The Clement Palo Alto (All-Inclusive Luxury)",
        category: "hotel",
        lat: 37.4442,
        lng: -122.1651,
        address: "711 El Camino Real, Palo Alto, CA 94301",
      },
      {
        id: "sc-htl-4",
        name: "Tetra Hotel, Autograph Collection",
        category: "hotel",
        lat: 37.4011,
        lng: -122.0252,
        address: "400 Valley Way, Milpitas, CA 95035",
      },
      // --- SHOPPING ---
      {
        id: "sc-shp-1",
        name: "Santana Row Luxury Dining & Retail",
        category: "shopping",
        lat: 37.3204,
        lng: -121.9475,
        address: "377 Santana Row, San Jose, CA 95128",
      },
      {
        id: "sc-shp-2",
        name: "Stanford Shopping Center",
        category: "shopping",
        lat: 37.4428,
        lng: -122.1712,
        address: "660 Stanford Shopping Center, Palo Alto, CA 94304",
      },
      {
        id: "sc-shp-3",
        name: "Westfield Valley Fair",
        category: "shopping",
        lat: 37.3252,
        lng: -121.9453,
        address: "2855 Stevens Creek Blvd, Santa Clara, CA 95050",
      },
      {
        id: "sc-shp-4",
        name: "Great Mall",
        category: "shopping",
        lat: 37.4144,
        lng: -121.8986,
        address: "447 Great Mall Dr, Milpitas, CA 95035",
      },
      // --- UNIVERSITIES ---
      {
        id: "sc-uni-1",
        name: "Stanford University",
        category: "university",
        lat: 37.4275,
        lng: -122.1697,
        address: "450 Serra Mall, Stanford, CA 94305",
      },
      {
        id: "sc-uni-2",
        name: "Santa Clara University",
        category: "university",
        lat: 37.3489,
        lng: -121.9367,
        address: "500 El Camino Real, Santa Clara, CA 95053",
      },
      {
        id: "sc-uni-3",
        name: "San Jose State University",
        category: "university",
        lat: 37.3352,
        lng: -121.8811,
        address: "1 Washington Sq, San Jose, CA 95192",
      },
      {
        id: "sc-uni-4",
        name: "Stanford Graduate School of Business",
        category: "university",
        lat: 37.429,
        lng: -122.1601,
        address: "655 Knight Way, Stanford, CA 94305",
      },
      // --- ATTRACTIONS ---
      {
        id: "sc-att-1",
        name: "Levi's Stadium",
        category: "attraction",
        lat: 37.4033,
        lng: -121.9694,
        address: "4900 Marie P DeBartolo Way, Santa Clara, CA 95054",
      },
      {
        id: "sc-att-2",
        name: "SAP Center at San Jose (Shark Tank VIP)",
        category: "attraction",
        lat: 37.3328,
        lng: -121.9012,
        address: "525 W Santa Clara St, San Jose, CA 95113",
      },
      {
        id: "sc-att-3",
        name: "Mountain Winery",
        category: "attraction",
        lat: 37.2411,
        lng: -122.0628,
        address: "14831 Pierce Rd, Saratoga, CA 95070",
      },
      {
        id: "sc-att-4",
        name: "Winchester Mystery House",
        category: "attraction",
        lat: 37.3184,
        lng: -121.9511,
        address: "525 S Winchester Blvd, San Jose, CA 95128",
      },
      // --- BUSINESS ---
      {
        id: "sc-bus-1",
        name: "Apple Park Corporate Headquarters",
        category: "business",
        lat: 37.3346,
        lng: -122.009,
        address: "One Apple Park Way, Cupertino, CA 95014",
      },
      {
        id: "sc-bus-2",
        name: "Googleplex (Google HQ)",
        category: "business",
        lat: 37.422,
        lng: -122.0841,
        address: "1600 Amphitheatre Pkwy, Mountain View, CA 94043",
      },
      {
        id: "sc-bus-3",
        name: "NVIDIA Corporate Headquarters",
        category: "business",
        lat: 37.3711,
        lng: -121.9642,
        address: "2788 San Tomas Expy, Santa Clara, CA 95051",
      },
      {
        id: "sc-bus-4",
        name: "Meta HQ (Classic Campus)",
        category: "business",
        lat: 37.4852,
        lng: -122.1483,
        address: "1 Hacker Way, Menlo Park, CA 94025",
      },
    ],
  },
  {
    id: "co-alameda",
    name: "East Bay",
    places: [
      // --- AIRPORTS & FBOs ---
      {
        id: "al-air-1",
        name: "Oakland International Airport (OAK)",
        category: "airport",
        lat: 37.7124,
        lng: -122.2132,
        address: "1 Canal Rd, Oakland, CA 94621",
      },
      {
        id: "al-air-2",
        name: "Signature Aviation OAK (Private Aviation Terminal)",
        category: "airport",
        lat: 37.7145,
        lng: -122.221,
        address: "8433 Earhart Rd, Oakland, CA 94621",
      },
      {
        id: "al-air-3",
        name: "Livermore Municipal Airport",
        category: "airport",
        lat: 37.6934,
        lng: -121.8202,
        address: "680 Terminal Cir, Livermore, CA 94551",
      },
      {
        id: "cc-air-1",
        name: "Buchanan Field Airport (East Bay Corporate Charters)",
        category: "airport",
        lat: 37.9904,
        lng: -122.0565,
        address: "550 Sally Ride Way, Concord, CA 94520",
      },
      {
        id: "al-air-4",
        name: "Hayward Executive Airport",
        category: "airport",
        lat: 37.6588,
        lng: -122.1217,
        address: "20301 Skywest Dr, Hayward, CA 94541",
      },
      // --- HOTELS ---
      {
        id: "al-htl-1",
        name: "Claremont Club & Spa - A Fairmont Hotel",
        category: "hotel",
        lat: 37.8569,
        lng: -122.2444,
        address: "41 Tunnel Rd, Berkeley, CA 94705",
      },
      {
        id: "al-htl-2",
        name: "The Berkeley Lasells Luxury Corporate Stays",
        category: "hotel",
        lat: 37.869,
        lng: -122.251,
        address: "2515 Piedmont Ave, Berkeley, CA 94704",
      },
      {
        id: "al-htl-3",
        name: "Residence Inn by Marriott Oakland Downtown",
        category: "hotel",
        lat: 37.8041,
        lng: -122.2709,
        address: "2530 Broadway, Oakland, CA 94612",
      },
      {
        id: "al-htl-4",
        name: "DoubleTree by Hilton Hotel Newark-Fremont",
        category: "hotel",
        lat: 37.5252,
        lng: -122.0345,
        address: "39900 Balentine Dr, Newark, CA 94560",
      },
      // --- SHOPPING ---
      {
        id: "al-shp-1",
        name: "San Francisco Premium Outlets",
        category: "shopping",
        lat: 37.6981,
        lng: -121.8441,
        address: "2774 Livermore Outlets Dr, Livermore, CA 94551",
      },
      {
        id: "al-shp-2",
        name: "Bay Street Emeryville",
        category: "shopping",
        lat: 37.8344,
        lng: -122.2921,
        address: "5616 Bay St, Emeryville, CA 94608",
      },
      {
        id: "al-shp-3",
        name: "Newpark Mall",
        category: "shopping",
        lat: 37.5264,
        lng: -122.0121,
        address: "2086 Newpark Mall, Newark, CA 94560",
      },
      {
        id: "al-shp-4",
        name: "Southland Mall",
        category: "shopping",
        lat: 37.6517,
        lng: -122.1025,
        address: "One Southland Mall, Hayward, CA 94545",
      },
      // --- UNIVERSITIES ---
      {
        id: "al-uni-1",
        name: "University of California, Berkeley",
        category: "university",
        lat: 37.8719,
        lng: -122.2585,
        address: "Berkeley, CA 94720",
      },
      {
        id: "al-uni-2",
        name: "California State University, East Bay",
        category: "university",
        lat: 37.6582,
        lng: -122.0545,
        address: "25800 Carlos Bee Blvd, Hayward, CA 94542",
      },
      {
        id: "al-uni-3",
        name: "Saint Mary's College (Satellite Campus)",
        category: "university",
        lat: 37.7012,
        lng: -121.8611,
        address: "Exhibit Way, Dublin, CA 94568",
      },
      {
        id: "al-uni-4",
        name: "Ohlone College",
        category: "university",
        lat: 37.5278,
        lng: -121.9167,
        address: "43600 Mission Blvd, Fremont, CA 94539",
      },
      // --- ATTRACTIONS ---
      {
        id: "al-att-1",
        name: "Wente Vineyards (Wine Tours & Golf)",
        category: "attraction",
        lat: 37.6585,
        lng: -121.7161,
        address: "5050 Arroyo Rd, Livermore, CA 94550",
      },
      {
        id: "al-att-2",
        name: "Oakland Arena & Coliseum",
        category: "attraction",
        lat: 37.7516,
        lng: -122.2005,
        address: "7000 Coliseum Way, Oakland, CA 94621",
      },
      {
        id: "al-att-3",
        name: "Fox Theater Oakland (Music Events)",
        category: "attraction",
        lat: 37.808,
        lng: -122.2711,
        address: "1807 Telegraph Ave, Oakland, CA 94612",
      },
      {
        id: "al-att-4",
        name: "Concannon Vineyard (High-end Gala Events)",
        category: "attraction",
        lat: 37.6522,
        lng: -121.737,
        address: "4590 Tesla Rd, Livermore, CA 94550",
      },
      // --- BUSINESS ---
      {
        id: "al-bus-1",
        name: "Tesla Factory Fremont (Executive Transport Hub)",
        category: "business",
        lat: 37.4924,
        lng: -121.9389,
        address: "45500 Fremont Blvd, Fremont, CA 94538",
      },
      {
        id: "al-bus-2",
        name: "Lawrence Livermore National Laboratory",
        category: "business",
        lat: 37.6854,
        lng: -121.7011,
        address: "7000 East Ave, Livermore, CA 94550",
      },
      {
        id: "al-bus-3",
        name: "Workday Corporate HQ",
        category: "business",
        lat: 37.6974,
        lng: -121.9262,
        address: "6110 Stoneridge Mall Rd, Pleasanton, CA 94588",
      },
      {
        id: "al-bus-4",
        name: "Kaiser Permanente Corporate Offices",
        category: "business",
        lat: 37.8105,
        lng: -122.2647,
        address: "1 Kaiser Plaza, Oakland, CA 94612",
      },
    ],
  },
  {
    id: "co-sacramento",
    name: "Sacramento County",
    places: [
      // --- AIRPORTS & FBOs ---
      {
        id: "sac-air-1",
        name: "Sacramento International Airport (SMF)",
        category: "airport",
        lat: 38.6954,
        lng: -121.5908,
        address: "6900 Airport Blvd, Sacramento, CA 95837",
      },
      {
        id: "sac-air-2",
        name: "Sacramento Executive Airport",
        category: "airport",
        lat: 38.5125,
        lng: -121.4934,
        address: "6151 Freeport Blvd, Sacramento, CA 95822",
      },
      {
        id: "sac-air-3",
        name: "Mather Airport (Cargo & Private Charter Hub)",
        category: "airport",
        lat: 38.5539,
        lng: -121.2975,
        address: "10510 Superfortress Ave, Mather, CA 95655",
      },
      {
        id: "sac-air-4",
        name: "Sacramento International Jet Center FBO",
        category: "airport",
        lat: 38.6888,
        lng: -121.5811,
        address: "5885 Flightline Dr, Sacramento, CA 95837",
      },
      // --- HOTELS ---
      {
        id: "sac-htl-1",
        name: "The Citizen Hotel, Autograph Collection",
        category: "hotel",
        lat: 38.5815,
        lng: -121.4931,
        address: "926 J St, Sacramento, CA 95814",
      },
      {
        id: "sac-htl-2",
        name: "Kimpton Sawyer Hotel (DOCO Executive Hub)",
        category: "hotel",
        lat: 38.5822,
        lng: -121.4994,
        address: "500 J St, Sacramento, CA 95814",
      },
      {
        id: "sac-htl-3",
        name: "Hyatt Regency Sacramento (State Capital VIP Hub)",
        category: "hotel",
        lat: 38.5772,
        lng: -121.4897,
        address: "1209 L St, Sacramento, CA 95814",
      },
      {
        id: "sac-htl-4",
        name: "The Westin Sacramento",
        category: "hotel",
        lat: 38.5411,
        lng: -121.5122,
        address: "4350 Riverside Blvd, Sacramento, CA 95822",
      },
      // --- SHOPPING ---
      {
        id: "sac-shp-1",
        name: "Arden Fair Mall",
        category: "shopping",
        lat: 38.5994,
        lng: -121.4286,
        address: "1689 Arden Way, Sacramento, CA 95815",
      },
      {
        id: "sac-shp-2",
        name: "Palladio Shopping Center",
        category: "shopping",
        lat: 38.6481,
        lng: -121.1011,
        address: "410 Palladio Pkwy, Folsom, CA 95630",
      },
      {
        id: "sac-shp-3",
        name: "Downtown Commons (DOCO Retail)",
        category: "shopping",
        lat: 38.5811,
        lng: -121.4975,
        address: "405 K St, Sacramento, CA 95814",
      },
      {
        id: "sac-shp-4",
        name: "Pavilions Shopping Center Luxury Boutiques",
        category: "shopping",
        lat: 38.5912,
        lng: -121.4111,
        address: "563 Fair Oaks Blvd, Sacramento, CA 95825",
      },
      // --- UNIVERSITIES ---
      {
        id: "sac-uni-1",
        name: "California State University, Sacramento",
        category: "university",
        lat: 38.5604,
        lng: -121.4245,
        address: "6000 J St, Sacramento, CA 95819",
      },
      {
        id: "sac-uni-2",
        name: "UC Davis Health Medical Education Center",
        category: "university",
        lat: 38.5539,
        lng: -121.4552,
        address: "4610 X St, Sacramento, CA 95817",
      },
      {
        id: "sac-uni-3",
        name: "McGeorge School of Law (University of the Pacific)",
        category: "university",
        lat: 38.5489,
        lng: -121.4745,
        address: "3200 Fifth Ave, Sacramento, CA 95817",
      },
      {
        id: "sac-uni-4",
        name: "American River College",
        category: "university",
        lat: 38.6489,
        lng: -121.3712,
        address: "4700 College Oak Dr, Sacramento, CA 95841",
      },
      // --- ATTRACTIONS ---
      {
        id: "sac-att-1",
        name: "Golden 1 Center (Executive Gate)",
        category: "attraction",
        lat: 38.5814,
        lng: -121.4991,
        address: "500 David J Stern Walk, Sacramento, CA 95814",
      },
      {
        id: "sac-att-2",
        name: "California State Capitol Museum (Political Transport)",
        category: "attraction",
        lat: 38.5767,
        lng: -121.4934,
        address: "1315 10th St, Sacramento, CA 95814",
      },
      {
        id: "sac-att-3",
        name: "SAFE Credit Union Convention Center (Corporate Galas)",
        category: "attraction",
        lat: 38.5785,
        lng: -121.4862,
        address: "1400 J St, Sacramento, CA 95814",
      },
      {
        id: "sac-att-4",
        name: "Sutter Health Park (VIP Corporate Suites)",
        category: "attraction",
        lat: 38.5794,
        lng: -121.511,
        address: "400 Ballpark Dr, West Sacramento, CA 95691",
      },
      // --- BUSINESS ---
      {
        id: "sac-bus-1",
        name: "Intel Corporation Folsom Campus",
        category: "business",
        lat: 38.6511,
        lng: -121.1398,
        address: "1900 Prairie City Rd, Folsom, CA 95630",
      },
      {
        id: "sac-bus-2",
        name: "VSP Global Corporate Headquarters",
        category: "business",
        lat: 38.6942,
        lng: -121.2891,
        address: "3333 Quality Dr, Rancho Cordova, CA 95670",
      },
      {
        id: "sac-bus-3",
        name: "Aerojet Rocketdyne Holdings Offices",
        category: "business",
        lat: 38.6411,
        lng: -121.1894,
        address: "2001 Aerojet Rd, Rancho Cordova, CA 95742",
      },
      {
        id: "sac-bus-4",
        name: "California Department of Technology HQ",
        category: "business",
        lat: 38.5912,
        lng: -121.439,
        address: "10860 Gold Center Dr, Rancho Cordova, CA 95670",
      },
    ],
  },
  {
    id: "co-san-mateo",
    name: "San Mateo County",
    places: [
      // --- AIRPORTS & FBOs ---
      {
        id: "sm-air-1",
        name: "San Carlos Airport (VIP Turboprop & Jet Charters)",
        category: "airport",
        lat: 37.5118,
        lng: -122.2494,
        address: "620 Airport Way, San Carlos, CA 94070",
      },
      {
        id: "sm-air-2",
        name: "Half Moon Bay Airport",
        category: "airport",
        lat: 37.5135,
        lng: -122.5011,
        address: "9850 Cabrillo Hwy N, Half Moon Bay, CA 94019",
      },
      {
        id: "sm-air-3",
        name: "Signature Aviation SQL (San Carlos FBO)",
        category: "airport",
        lat: 37.513,
        lng: -122.248,
        address: "790 Airport Way, San Carlos, CA 94070",
      },
      {
        id: "sm-air-4",
        name: "SFO Signature Aviation South Terminal",
        category: "airport",
        lat: 37.6322,
        lng: -122.3855,
        address: "640 Airport Blvd, South San Francisco, CA 94080",
      },
      // --- HOTELS ---
      {
        id: "sm-htl-1",
        name: "The Ritz-Carlton, Half Moon Bay (Elite Wedding/Golf)",
        category: "hotel",
        lat: 37.4332,
        lng: -122.4414,
        address: "1 Miramontes Point Rd, Half Moon Bay, CA 94019",
      },
      {
        id: "sm-htl-2",
        name: "The Westin San Francisco Airport",
        category: "hotel",
        lat: 37.5991,
        lng: -122.3664,
        address: "1 Old Bayshore Hwy, Millbrae, CA 94030",
      },
      {
        id: "sm-htl-3",
        name: "Grand Hyatt at SFO (VIP Layover & Board Meetings)",
        category: "hotel",
        lat: 37.6241,
        lng: -122.3888,
        address: "55 South McDonnell Rd, San Francisco, CA 94128",
      },
      {
        id: "sm-htl-4",
        name: "Four Seasons Hotel Silicon Valley at East Palo Alto",
        category: "hotel",
        lat: 37.4611,
        lng: -122.1388,
        address: "2050 University Ave, East Palo Alto, CA 94303",
      },
      // --- SHOPPING ---
      {
        id: "sm-shp-1",
        name: "Hillsdale Shopping Center",
        category: "shopping",
        lat: 37.5401,
        lng: -122.2989,
        address: "60 31st Ave, San Mateo, CA 94403",
      },
      {
        id: "sm-shp-2",
        name: "Serramonte Center",
        category: "shopping",
        lat: 37.6698,
        lng: -122.4691,
        address: "3 Serramonte Center, Daly City, CA 94015",
      },
      {
        id: "sm-shp-3",
        name: "The Shops at Tanforan",
        category: "shopping",
        lat: 37.6375,
        lng: -122.4172,
        address: "1150 El Camino Real, San Bruno, CA 94066",
      },
      {
        id: "sm-shp-4",
        name: "Town & Country Village Retail (Border Area)",
        category: "shopping",
        lat: 37.4435,
        lng: -122.1622,
        address: "855 El Camino Real, Palo Alto, CA 94301",
      },
      // --- UNIVERSITIES ---
      {
        id: "sm-uni-1",
        name: "Notre Dame de Namur University",
        category: "university",
        lat: 37.5161,
        lng: -122.2858,
        address: "1500 Ralston Ave, Belmont, CA 94002",
      },
      {
        id: "sm-uni-2",
        name: "College of San Mateo",
        category: "university",
        lat: 37.5372,
        lng: -122.3214,
        address: "1700 W Hillsdale Blvd, San Mateo, CA 94402",
      },
      {
        id: "sm-uni-3",
        name: "Cañada College",
        category: "university",
        lat: 37.4398,
        lng: -122.2575,
        address: "4200 Farm Hill Blvd, Redwood City, CA 94061",
      },
      {
        id: "sm-uni-4",
        name: "Skyline College",
        category: "university",
        lat: 37.6294,
        lng: -122.467,
        address: "3300 College Dr, San Bruno, CA 94066",
      },
      // --- ATTRACTIONS ---
      {
        id: "sm-att-1",
        name: "Filoli Historic House and Garden",
        category: "attraction",
        lat: 37.4704,
        lng: -122.3117,
        address: "86 Cañada Rd, Woodside, CA 94062",
      },
      {
        id: "sm-att-2",
        name: "Coyote Point Recreation Area",
        category: "attraction",
        lat: 37.5912,
        lng: -122.3189,
        address: "1701 Coyote Point Drive, San Mateo, CA 94401",
      },
      {
        id: "sm-att-3",
        name: "Bay Meadows Event Spaces",
        category: "attraction",
        lat: 37.5422,
        lng: -122.2965,
        address: "3180 Kyne St, San Mateo, CA 94403",
      },
      {
        id: "sm-att-4",
        name: "Rockaway Beach (Coastal Tour Stop)",
        category: "attraction",
        lat: 37.6111,
        lng: -122.4965,
        address: "Rockaway Beach Ave, Pacifica, CA 94044",
      },
      // --- BUSINESS ---
      {
        id: "sm-bus-1",
        name: "Oracle Corporate Headquarters Campus",
        category: "business",
        lat: 37.5294,
        lng: -122.2662,
        address: "2300 Oracle Pkwy, Redwood City, CA 94065",
      },
      {
        id: "sm-bus-2",
        name: "Electronic Arts (EA) Corporate HQ",
        category: "business",
        lat: 37.5255,
        lng: -122.2536,
        address: "209 Redwood Shores Pkwy, Redwood City, CA 94065",
      },
      {
        id: "sm-bus-3",
        name: "Genentech Corporate Headquarters",
        category: "business",
        lat: 37.6611,
        lng: -122.3905,
        address: "1 DNA Way, South San Francisco, CA 94080",
      },
      {
        id: "sm-bus-4",
        name: "YouTube HQ Executive Towers",
        category: "business",
        lat: 37.6281,
        lng: -122.4211,
        address: "901 Cherry Ave, San Bruno, CA 94066",
      },
    ],
  },
  {
    id: "co-contra-costa",
    name: "Contra Costa County",
    places: [
      // --- AIRPORTS & FBOs ---
      {
        id: "cc-air-2",
        name: "Byron Airport (Private Skydive & Charter Aviation)",
        category: "airport",
        lat: 37.8347,
        lng: -121.6325,
        address: "3091 Armstrong Rd, Byron, CA 94514",
      },
      {
        id: "cc-air-3",
        name: "Sterling Aviation Concord (Executive FBO)",
        category: "airport",
        lat: 37.993,
        lng: -122.0511,
        address: "181 John Glenn Dr, Concord, CA 94520",
      },
      {
        id: "cc-air-4",
        name: "Pacific States Aviation FBO",
        category: "airport",
        lat: 37.9952,
        lng: -122.0544,
        address: "81 John Glenn Dr, Concord, CA 94520",
      },
      // --- HOTELS ---
      {
        id: "cc-htl-1",
        name: "Lafayette Park Hotel & Spa",
        category: "hotel",
        lat: 37.8924,
        lng: -122.0945,
        address: "3287 Mt Diablo Blvd, Lafayette, CA 94549",
      },
      {
        id: "cc-htl-2",
        name: "Renaissance Walnut Creek Hotel",
        category: "hotel",
        lat: 37.9272,
        lng: -122.0594,
        address: "2805 Jones Rd, Walnut Creek, CA 94597",
      },
      {
        id: "cc-htl-3",
        name: "The Claremont (Contra Costa Border Alignment)",
        category: "hotel",
        lat: 37.8571,
        lng: -122.2435,
        address: "41 Tunnel Rd, Berkeley, CA 94705",
      },
      {
        id: "cc-htl-4",
        name: "San Ramon Marriott (Chevron Executive Stay Hub)",
        category: "hotel",
        lat: 37.7589,
        lng: -121.9611,
        address: "2600 Bishop Dr, San Ramon, CA 94583",
      },
      // --- SHOPPING ---
      {
        id: "cc-shp-1",
        name: "Broadway Plaza Premium Shopping District",
        category: "shopping",
        lat: 37.8953,
        lng: -122.0583,
        address: "1275 Broadway Plaza, Walnut Creek, CA 94596",
      },
      {
        id: "cc-shp-2",
        name: "The Veranda Retail Center",
        category: "shopping",
        lat: 37.9731,
        lng: -122.0589,
        address: "2001 Diamond Blvd, Concord, CA 94520",
      },
      {
        id: "cc-shp-3",
        name: "City Center Bishop Ranch (Upscale Open-Air Retail)",
        category: "shopping",
        lat: 37.7611,
        lng: -121.9544,
        address: "6000 Bollinger Canyon Rd, San Ramon, CA 94583",
      },
      {
        id: "cc-shp-4",
        name: "Sunvalley Shopping Center",
        category: "shopping",
        lat: 37.9705,
        lng: -122.062,
        address: "1 Sunvalley Mall, Concord, CA 94520",
      },
      // --- UNIVERSITIES ---
      {
        id: "cc-uni-1",
        name: "Saint Mary's College of California",
        category: "university",
        lat: 37.8415,
        lng: -122.1092,
        address: "1928 St Marys Rd, Moraga, CA 94556",
      },
      {
        id: "cc-uni-2",
        name: "Diablo Valley College (DVC)",
        category: "university",
        lat: 37.9698,
        lng: -122.0722,
        address: "321 Golf Club Rd, Pleasant Hill, CA 94523",
      },
      {
        id: "cc-uni-3",
        name: "California State University (Concord Campus)",
        category: "university",
        lat: 37.9352,
        lng: -121.9758,
        address: "4700 Ygnacio Valley Rd, Concord, CA 94521",
      },
      {
        id: "cc-uni-4",
        name: "Los Medanos College",
        category: "university",
        lat: 38.0167,
        lng: -121.8745,
        address: "2700 E Leland Rd, Pittsburg, CA 94565",
      },
      // --- ATTRACTIONS ---
      {
        id: "cc-att-1",
        name: "Mount Diablo State Park Summit",
        category: "attraction",
        lat: 37.8816,
        lng: -121.9142,
        address: "Summit Rd, Walnut Creek, CA 94598",
      },
      {
        id: "cc-att-2",
        name: "Blackhawk Museum (High-End Corporate/Gala Venue)",
        category: "attraction",
        lat: 37.7989,
        lng: -121.9114,
        address: "3700 Blackhawk Plaza Circle, Danville, CA 94506",
      },
      {
        id: "cc-att-3",
        name: "Lesher Center for the Arts",
        category: "attraction",
        lat: 37.9011,
        lng: -122.0611,
        address: "1601 Civic Dr, Walnut Creek, CA 94596",
      },
      {
        id: "cc-att-4",
        name: "John Muir National Historic Site",
        category: "attraction",
        lat: 37.9972,
        lng: -122.1317,
        address: "4202 Alhambra Ave, Martinez, CA 94553",
      },
      // --- BUSINESS ---
      {
        id: "cc-bus-1",
        name: "Chevron Richmond Refinery Corporate HQ",
        category: "business",
        lat: 37.9472,
        lng: -122.3946,
        address: "841 Chevron Way, Richmond, CA 94801",
      },
      {
        id: "cc-bus-2",
        name: "Bishop Ranch Executive Corporate Park",
        category: "business",
        lat: 37.7655,
        lng: -121.9567,
        address: "2600 Camino Ramon, San Ramon, CA 94583",
      },
      {
        id: "cc-bus-3",
        name: "Bank of America Concord Technology Center",
        category: "business",
        lat: 37.9811,
        lng: -122.0545,
        address: "2000 Clayton Rd, Concord, CA 94520",
      },
      {
        id: "cc-bus-4",
        name: "AAA Northern California HQ",
        category: "business",
        lat: 37.9542,
        lng: -122.0611,
        address: "3055 Willow Pass Rd, Concord, CA 94519",
      },
    ],
  },
  {
    id: "co-sonoma",
    name: "Sonoma County",
    places: [
      // --- AIRPORTS & FBOs ---
      {
        id: "son-air-1",
        name: "Charles M. Schulz-Sonoma County Airport (STS)",
        category: "airport",
        lat: 38.5089,
        lng: -122.8128,
        address: "2200 Airport Blvd, Santa Rosa, CA 95403",
      },
      {
        id: "son-air-2",
        name: "Sonoma Jet Center (Elite Wine Country FBO)",
        category: "airport",
        lat: 38.5115,
        lng: -122.809,
        address: "6000 Flightline Dr, Santa Rosa, CA 95403",
      },
      {
        id: "son-air-3",
        name: "Petaluma Municipal Airport",
        category: "airport",
        lat: 38.2585,
        lng: -122.6052,
        address: "601 Sky Ranch Dr, Petaluma, CA 94954",
      },
      {
        id: "son-air-4",
        name: "Healdsburg Municipal Airport",
        category: "airport",
        lat: 38.6439,
        lng: -122.8986,
        address: "1 Airline Way, Healdsburg, CA 95448",
      },
      // --- HOTELS ---
      {
        id: "son-htl-1",
        name: "Fairmont Sonoma Mission Inn & Spa",
        category: "hotel",
        lat: 38.3149,
        lng: -122.4801,
        address: "100 Boyes Blvd, Sonoma, CA 95476",
      },
      {
        id: "son-htl-2",
        name: "Montage Healdsburg (Ultra-Luxury Resort Hub)",
        category: "hotel",
        lat: 38.6512,
        lng: -122.8647,
        address: "100 Montage Way, Healdsburg, CA 95448",
      },
      {
        id: "son-htl-3",
        name: "Hotel Les Mars (Relais & Châteaux)",
        category: "hotel",
        lat: 38.6118,
        lng: -122.8694,
        address: "27 North St, Healdsburg, CA 95448",
      },
      {
        id: "son-htl-4",
        name: "MacArthur Place Hotel & Spa",
        category: "hotel",
        lat: 38.2867,
        lng: -122.4589,
        address: "29 E MacArthur St, Sonoma, CA 95476",
      },
      // --- SHOPPING ---
      {
        id: "son-shp-1",
        name: "Santa Rosa Plaza",
        category: "shopping",
        lat: 38.4385,
        lng: -122.7196,
        address: "1071 Santa Rosa Plaza, Santa Rosa, CA 95401",
      },
      {
        id: "son-shp-2",
        name: "Healdsburg Plaza Luxury Retail District",
        category: "shopping",
        lat: 38.6105,
        lng: -122.8692,
        address: "Healdsburg Ave, Healdsburg, CA 95448",
      },
      {
        id: "son-shp-3",
        name: "Petaluma Village Premium Outlets",
        category: "shopping",
        lat: 38.2675,
        lng: -122.6611,
        address: "2200 Petaluma Blvd N, Petaluma, CA 94952",
      },
      {
        id: "son-shp-4",
        name: "Montgomery Village Outdoor Lifestyle Center",
        category: "shopping",
        lat: 38.4422,
        lng: -122.6888,
        address: "911 Village Ct, Santa Rosa, CA 95405",
      },
      // --- UNIVERSITIES ---
      {
        id: "son-uni-1",
        name: "Sonoma State University",
        category: "university",
        lat: 38.3392,
        lng: -122.6744,
        address: "1801 East Cotati Ave, Rohnert Park, CA 94928",
      },
      {
        id: "son-uni-2",
        name: "Santa Rosa Junior College (SRJC)",
        category: "university",
        lat: 38.4552,
        lng: -122.7214,
        address: "1501 Mendocino Ave, Santa Rosa, CA 95401",
      },
      {
        id: "son-uni-3",
        name: "SRJC Petaluma Campus",
        category: "university",
        lat: 38.2461,
        lng: -122.6111,
        address: "680 Sonoma Mountain Pkwy, Petaluma, CA 94954",
      },
      {
        id: "son-uni-4",
        name: "Empire College School of Law",
        category: "university",
        lat: 38.4711,
        lng: -122.7385,
        address: "3035 Cleveland Ave, Santa Rosa, CA 95403",
      },
      // --- ATTRACTIONS (Elite Wedding / Chauffeur Wine Tours) ---
      {
        id: "son-att-1",
        name: "Safari West Wildlife Preserve",
        category: "attraction",
        lat: 38.5471,
        lng: -122.7153,
        address: "3115 Porter Creek Rd, Santa Rosa, CA 95404",
      },
      {
        id: "son-att-2",
        name: "Buena Vista Winery (Historic Event Space)",
        category: "attraction",
        lat: 38.3011,
        lng: -122.4212,
        address: "18000 Old Winery Rd, Sonoma, CA 95476",
      },
      {
        id: "son-att-3",
        name: "Ferrari-Carano Tramonto Vineyards",
        category: "attraction",
        lat: 38.7188,
        lng: -122.9744,
        address: "8761 Dry Creek Rd, Healdsburg, CA 95448",
      },
      {
        id: "son-att-4",
        name: "Sonoma Raceway (VIP Executive Chalets)",
        category: "attraction",
        lat: 38.1611,
        lng: -122.4594,
        address: "29355 Arnold Dr, Sonoma, CA 95476",
      },
      // --- BUSINESS ---
      {
        id: "son-bus-1",
        name: "Kendall-Jackson Wine Estate & Gardens HQ",
        category: "business",
        lat: 38.5255,
        lng: -122.7599,
        address: "5007 Fulton Rd, Santa Rosa, CA 95403",
      },
      {
        id: "son-bus-2",
        name: "Francis Ford Coppola Winery Corporate Office",
        category: "business",
        lat: 38.6822,
        lng: -122.8894,
        address: "300 Via James Coppola, Geyserville, CA 95441",
      },
      {
        id: "son-bus-3",
        name: "Keysight Technologies Corporate Headquarters",
        category: "business",
        lat: 38.4774,
        lng: -122.709,
        address: "1400 Fountaingrove Pkwy, Santa Rosa, CA 95403",
      },
      {
        id: "son-bus-4",
        name: "Enphase Energy Corporate Offices",
        category: "business",
        lat: 38.4411,
        lng: -122.7144,
        address: "4728 Old Redwood Hwy, Santa Rosa, CA 95403",
      },
    ],
  },
  {
    id: "co-napa",
    name: "Napa County",
    places: [
      // --- AIRPORTS & FBOs ---
      {
        id: "np-air-1",
        name: "Napa County Airport (APC)",
        category: "airport",
        lat: 38.2132,
        lng: -122.2806,
        address: "2030 Airport Rd, Napa, CA 94558",
      },
      {
        id: "np-air-2",
        name: "Atlantic Aviation APC (Primary Wine Country Jet Terminal)",
        category: "airport",
        lat: 38.2115,
        lng: -122.2844,
        address: "2000 Airport Rd, Napa, CA 94558",
      },
      {
        id: "np-air-3",
        name: "Angwin-Parrett Field",
        category: "airport",
        lat: 38.5802,
        lng: -122.4394,
        address: "100 Airport Rd, Angwin, CA 94508",
      },
      {
        id: "np-air-4",
        name: "Napa Jet Charter Terminal",
        category: "airport",
        lat: 38.2155,
        lng: -122.2799,
        address: "2010 Airport Rd, Napa, CA 94558",
      },
      // --- HOTELS (Massive Chauffeur Destinations) ---
      {
        id: "np-htl-1",
        name: "Auberge du Soleil Ultra-Luxury Resort",
        category: "hotel",
        lat: 38.4819,
        lng: -122.3739,
        address: "180 Rutherford Hill Rd, Rutherford, CA 94573",
      },
      {
        id: "np-htl-2",
        name: "Meadowood Napa Valley (Estate Wedding Hub)",
        category: "hotel",
        lat: 38.5211,
        lng: -122.4644,
        address: "900 Meadowood Lane, St. Helena, CA 94574",
      },
      {
        id: "np-htl-3",
        name: "Stanly Ranch, Auberge Resorts Collection",
        category: "hotel",
        lat: 38.2575,
        lng: -122.2962,
        address: "200 Stanly Ranch Rd, Napa, CA 94559",
      },
      {
        id: "np-htl-4",
        name: "Carneros Resort and Spa",
        category: "hotel",
        lat: 38.2611,
        lng: -122.3511,
        address: "4048 Sonoma Hwy, Napa, CA 94559",
      },
      // --- SHOPPING ---
      {
        id: "np-shp-1",
        name: "Napa Premium Outlets",
        category: "shopping",
        lat: 38.2917,
        lng: -122.3023,
        address: "629 Factory Stores Dr, Napa, CA 94558",
      },
      {
        id: "np-shp-2",
        name: "Oxbow Public Market",
        category: "shopping",
        lat: 38.3031,
        lng: -122.2814,
        address: "610 1st St, Napa, CA 94559",
      },
      {
        id: "np-shp-3",
        name: "St. Helena Main Street Retail District",
        category: "shopping",
        lat: 38.5042,
        lng: -122.4689,
        address: "Main St, St. Helena, CA 94574",
      },
      {
        id: "np-shp-4",
        name: "First Street Napa Open-Air Shopping",
        category: "shopping",
        lat: 38.3012,
        lng: -122.2864,
        address: "1300 1st St, Napa, CA 94559",
      },
      // --- UNIVERSITIES ---
      {
        id: "np-uni-1",
        name: "Pacific Union College",
        category: "university",
        lat: 38.5714,
        lng: -122.4464,
        address: "1 Angwin Ave, Angwin, CA 94508",
      },
      {
        id: "np-uni-2",
        name: "The Culinary Institute of America at Greystone",
        category: "university",
        lat: 38.5111,
        lng: -122.4811,
        address: "2555 Main St, St. Helena, CA 94574",
      },
      {
        id: "np-uni-3",
        name: "Napa Valley College",
        category: "university",
        lat: 38.2755,
        lng: -122.2745,
        address: "2277 Napa Vallejo Hwy, Napa, CA 94558",
      },
      {
        id: "np-uni-4",
        name: "CIA at Copia (Culinary Arts Education Hub)",
        category: "university",
        lat: 38.3022,
        lng: -122.2801,
        address: "500 1st St, Napa, CA 94559",
      },
      // --- ATTRACTIONS (Prime Winery Chauffeur Packages) ---
      {
        id: "np-att-1",
        name: "Napa Valley Wine Train Depot",
        category: "attraction",
        lat: 38.3045,
        lng: -122.2831,
        address: "1275 McKinstry St, Napa, CA 94559",
      },
      {
        id: "np-att-2",
        name: "Castello di Amorosa (Castle Tours & Tastings)",
        category: "attraction",
        lat: 38.5942,
        lng: -122.5422,
        address: "4045 Saint Helena Hwy, Calistoga, CA 94515",
      },
      {
        id: "np-att-3",
        name: "V. Sattui Winery (High-Volume Event Shuttle Hub)",
        category: "attraction",
        lat: 38.4892,
        lng: -122.4514,
        address: "1111 White Lane, St. Helena, CA 94574",
      },
      {
        id: "np-att-4",
        name: "Opus One Winery (Ultra-VIP Executive Tastings)",
        category: "attraction",
        lat: 38.4411,
        lng: -122.4278,
        address: "7900 St. Helena Hwy, Oakville, CA 94562",
      },
      // --- BUSINESS ---
      {
        id: "np-bus-1",
        name: "Robert Mondavi Winery Estate HQ",
        category: "business",
        lat: 38.4321,
        lng: -122.4262,
        address: "7801 St Helena Hwy, Oakville, CA 94562",
      },
      {
        id: "np-bus-2",
        name: "The Hess Persson Estates Corporate Offices",
        category: "business",
        lat: 38.2974,
        lng: -122.3611,
        address: "4411 Redwood Rd, Napa, CA 94558",
      },
      {
        id: "np-bus-3",
        name: "Beringer Vineyards Executive HQ",
        category: "business",
        lat: 38.5105,
        lng: -122.4831,
        address: "2000 Main St, St. Helena, CA 94574",
      },
      {
        id: "np-bus-4",
        name: "Sutter Home Winery Corporate Complex",
        category: "business",
        lat: 38.4774,
        lng: -122.449,
        address: "277 St. Helena Hwy S, St. Helena, CA 94574",
      },
    ],
  },
  {
    id: "co-marin",
    name: "Marin County",
    places: [
      // --- AIRPORTS & FBOs ---
      {
        id: "mr-air-1",
        name: "Marin County Airport (Gnoss Field)",
        category: "airport",
        lat: 38.1435,
        lng: -122.5557,
        address: "451 Airport Rd, Novato, CA 94945",
      },
      {
        id: "mr-air-2",
        name: "Richardson Bay Heliport (VIP Marine-Air Shuttle)",
        category: "airport",
        lat: 37.8761,
        lng: -122.511,
        address: "100 Harbor Dr, Sausalito, CA 94965",
      },
      {
        id: "mr-air-3",
        name: "Gnoss Field Executive Charter Terminal",
        category: "airport",
        lat: 38.145,
        lng: -122.5511,
        address: "455 Airport Rd, Novato, CA 94945",
      },
      {
        id: "mr-air-4",
        name: "Commodore Center Seaplane Base",
        category: "airport",
        lat: 37.8794,
        lng: -122.5152,
        address: "242 Redwood Hwy, Mill Valley, CA 94941",
      },
      // --- HOTELS ---
      {
        id: "mr-htl-1",
        name: "Cavallo Point Lodge (Fort Baker Wedding Destination)",
        category: "hotel",
        lat: 37.8344,
        lng: -122.4789,
        address: "601 Murray Cir, Sausalito, CA 94965",
      },
      {
        id: "mr-htl-2",
        name: "Casa Madrona Hotel & Spa (VIP Yacht Charters)",
        category: "hotel",
        lat: 37.8552,
        lng: -122.4827,
        address: "801 Bridgeway, Sausalito, CA 94965",
      },
      {
        id: "mr-htl-3",
        name: "Acqua Hotel Mill Valley",
        category: "hotel",
        lat: 37.8922,
        lng: -122.5154,
        address: "555 Redwood Hwy, Mill Valley, CA 94941",
      },
      {
        id: "mr-htl-4",
        name: "The Inn at Roundstone Farm",
        category: "hotel",
        lat: 38.0122,
        lng: -122.7985,
        address: "9940 Sir Francis Drake Blvd, Olema, CA 94950",
      },
      // --- SHOPPING ---
      {
        id: "mr-shp-1",
        name: "The Village at Corte Madera Luxury Retail",
        category: "shopping",
        lat: 37.9272,
        lng: -122.5169,
        address: "1618 Redwood Hwy, Corte Madera, CA 94925",
      },
      {
        id: "mr-shp-2",
        name: "Town Center Corte Madera",
        category: "shopping",
        lat: 37.9298,
        lng: -122.5255,
        address: "100 Tamal Vista Blvd, Corte Madera, CA 94925",
      },
      {
        id: "mr-shp-3",
        name: "Strawberry Village Shopping Center",
        category: "shopping",
        lat: 37.8988,
        lng: -122.5141,
        address: "8000 Strawberry Village, Mill Valley, CA 94941",
      },
      {
        id: "mr-shp-4",
        name: "Marin Country Mart Plaza",
        category: "shopping",
        lat: 37.9442,
        lng: -122.511,
        address: "2257 Larkspur Landing Circle, Larkspur, CA 94939",
      },
      // --- UNIVERSITIES ---
      {
        id: "mr-uni-1",
        name: "Dominican University of California",
        category: "university",
        lat: 37.9806,
        lng: -122.5111,
        address: "50 Acacia Ave, San Rafael, CA 94901",
      },
      {
        id: "mr-uni-2",
        name: "College of Marin (Kentfield Campus)",
        category: "university",
        lat: 37.9542,
        lng: -122.5517,
        address: "835 College Ave, Kentfield, CA 94904",
      },
      {
        id: "mr-uni-3",
        name: "College of Marin (Indian Valley Campus)",
        category: "university",
        lat: 38.0945,
        lng: -122.5974,
        address: "1800 Ignacio Blvd, Novato, CA 94949",
      },
      {
        id: "mr-uni-4",
        name: "San Francisco Theological Seminary",
        category: "university",
        lat: 37.9691,
        lng: -122.5645,
        address: "105 Seminary Rd, San Anselmo, CA 94960",
      },
      // --- ATTRACTIONS ---
      {
        id: "mr-att-1",
        name: "Muir Woods National Monument",
        category: "attraction",
        lat: 37.8912,
        lng: -122.5734,
        address: "1 Muir Woods Rd, Mill Valley, CA 94941",
      },
      {
        id: "mr-att-2",
        name: "Marin County Civic Center (Frank Lloyd Wright Landmark)",
        category: "attraction",
        lat: 37.9978,
        lng: -122.5312,
        address: "3501 Civic Center Dr, San Rafael, CA 94903",
      },
      {
        id: "mr-att-3",
        name: "Point Reyes National Seashore Headlands",
        category: "attraction",
        lat: 37.9965,
        lng: -123.0224,
        address: "1 Bear Valley Rd, Point Reyes Station, CA 94956",
      },
      {
        id: "mr-att-4",
        name: "Larkspur Ferry Terminal",
        category: "attraction",
        lat: 37.9445,
        lng: -122.5089,
        address: "101 E Sir Francis Drake Blvd, Larkspur, CA 94939",
      },
      // --- BUSINESS ---
      {
        id: "mr-bus-1",
        name: "Skywalker Ranch Corporate Campus",
        category: "business",
        lat: 38.062,
        lng: -122.6528,
        address: "5858 Lucas Valley Rd, Nicasio, CA 94946",
      },
      {
        id: "mr-bus-2",
        name: "Autodesk Corporate Offices San Rafael",
        category: "business",
        lat: 37.9611,
        lng: -122.5145,
        address: "111 McInnis Pkwy, San Rafael, CA 94903",
      },
      {
        id: "mr-bus-3",
        name: "Glassdoor Corporate Headquarters Office",
        category: "business",
        lat: 37.8641,
        lng: -122.4889,
        address: "100 Shoreline Hwy, Mill Valley, CA 94941",
      },
      {
        id: "mr-bus-4",
        name: "BioMarin Pharmaceutical Corporate HQ",
        category: "business",
        lat: 37.9712,
        lng: -122.5185,
        address: "105 Digital Dr, Novato, CA 94949",
      },
    ],
  },
  {
    id: "co-yolo",
    name: "Yolo County",
    places: [
      // --- AIRPORTS & FBOs ---
      {
        id: "yl-air-1",
        name: "Yolo County Airport",
        category: "airport",
        lat: 38.5798,
        lng: -121.8566,
        address: "25170 Aviation Ave, Davis, CA 95616",
      },
      {
        id: "yl-air-2",
        name: "Watts-Woodland Airport",
        category: "airport",
        lat: 38.6745,
        lng: -121.8711,
        address: "17117 County Rd 94B, Woodland, CA 95695",
      },
      {
        id: "yl-air-3",
        name: "Davis University Airport",
        category: "airport",
        lat: 38.5355,
        lng: -121.782,
        address: "24950 County Rd 95, Davis, CA 95616",
      },
      {
        id: "yl-air-4",
        name: "Borges-Clarksburg Airport",
        category: "airport",
        lat: 38.4222,
        lng: -121.5211,
        address: "44115 County Rd 154, Clarksburg, CA 95612",
      },
      // --- HOTELS ---
      {
        id: "yl-htl-1",
        name: "Cache Creek Casino Resort Hotel",
        category: "hotel",
        lat: 38.7337,
        lng: -122.1416,
        address: "14455 CA-16, Brooks, CA 95606",
      },
      {
        id: "yl-htl-2",
        name: "Hyatt Regency Davis",
        category: "hotel",
        lat: 38.5365,
        lng: -121.7536,
        address: "4111 Dairy Rd, Davis, CA 95616",
      },
      {
        id: "yl-htl-3",
        name: "Hotel California Davis",
        category: "hotel",
        lat: 38.5442,
        lng: -121.7411,
        address: "241 B St, Davis, CA 95616",
      },
      {
        id: "yl-htl-4",
        name: "Staybridge Suites Sacramento Airport Natomas (Yolo Sector)",
        category: "hotel",
        lat: 38.6394,
        lng: -121.611,
        address: "1401 Harbor Blvd, West Sacramento, CA 95691",
      },
      // --- SHOPPING ---
      {
        id: "yl-shp-1",
        name: "County Fair Fashion Mall",
        category: "shopping",
        lat: 38.6891,
        lng: -121.7589,
        address: "1264 E Gibson Rd, Woodland, CA 95776",
      },
      {
        id: "yl-shp-2",
        name: "University Mall Davis",
        category: "shopping",
        lat: 38.5478,
        lng: -121.7511,
        address: "871 Russell Blvd, Davis, CA 95616",
      },
      {
        id: "yl-shp-3",
        name: "IKEA West Sacramento Retail Hub",
        category: "shopping",
        lat: 38.5689,
        lng: -121.5511,
        address: "700 Ikea Ct, West Sacramento, CA 95605",
      },
      {
        id: "yl-shp-4",
        name: "The Cannery Lifestyle Retail District",
        category: "shopping",
        lat: 38.5611,
        lng: -121.7345,
        address: "1111 Covell Blvd, Davis, CA 95616",
      },
      // --- UNIVERSITIES ---
      {
        id: "yl-uni-1",
        name: "University of California, Davis (Main Campus Hub)",
        category: "university",
        lat: 38.5382,
        lng: -121.7617,
        address: "1 Shields Ave, Davis, CA 95616",
      },
      {
        id: "yl-uni-2",
        name: "UC Davis School of Veterinary Medicine",
        category: "university",
        lat: 38.5342,
        lng: -121.7654,
        address: "944 Garrod Dr, Davis, CA 95616",
      },
      {
        id: "yl-uni-3",
        name: "Woodland Community College",
        category: "university",
        lat: 38.6589,
        lng: -121.7345,
        address: "2300 E Gibson Rd, Woodland, CA 95776",
      },
      {
        id: "yl-uni-4",
        name: "UC Davis School of Law (King Hall)",
        category: "university",
        lat: 38.5401,
        lng: -121.7554,
        address: "400 Mrak Hall Drive, Davis, CA 95616",
      },
      // --- ATTRACTIONS (Winery Weddings & Chauffeur Group Outings) ---
      {
        id: "yl-att-1",
        name: "The Old Sugar Mill Wineries",
        category: "attraction",
        lat: 38.4211,
        lng: -121.5612,
        address: "35265 Willow Ave, Clarksburg, CA 95612",
      },
      {
        id: "yl-att-2",
        name: "Sacramento River Train (Woodland Depot Trackage)",
        category: "attraction",
        lat: 38.6744,
        lng: -121.7423,
        address: "340 N East St, Woodland, CA 95776",
      },
      {
        id: "yl-att-3",
        name: "Mondavi Center for the Performing Arts",
        category: "attraction",
        lat: 38.5322,
        lng: -121.7505,
        address: "1 Shields Ave, Davis, CA 95616",
      },
      {
        id: "yl-att-4",
        name: "Yolo Bypass Wildlife Area Vista Point",
        category: "attraction",
        lat: 38.5535,
        lng: -121.6214,
        address: "45211 County Rd 32B, Davis, CA 95616",
      },
      // --- BUSINESS ---
      {
        id: "yl-bus-1",
        name: "Marrone Bio Innovations Headquarters",
        category: "business",
        lat: 38.5705,
        lng: -121.7538,
        address: "1540 Drew Ave, Davis, CA 95618",
      },
      {
        id: "yl-bus-2",
        name: "Nippon Sharyo Manufacturing Facilities Office",
        category: "business",
        lat: 38.5942,
        lng: -121.5422,
        address: "3700 Industrial Blvd, West Sacramento, CA 95691",
      },
      {
        id: "yl-bus-3",
        name: "Schilling Robotics Corporate Complex",
        category: "business",
        lat: 38.5711,
        lng: -121.7314,
        address: "201 Cousteau Pl, Davis, CA 95618",
      },
      {
        id: "yl-bus-4",
        name: "Raley's Corporate Headquarters",
        category: "business",
        lat: 38.5752,
        lng: -121.5211,
        address: "500 West Capitol Ave, West Sacramento, CA 95605",
      },
    ],
  },
];

export const defaultMapSuggestions: PlaceSuggestionType[] = [
  {
    name: "Mercado and Sacramento",
    mapbox_id:
      "dXJuOm1ieHBvaTpmNzRmMzA3OC00OGI2LTRlNTItOGMxZi0yMzI5Njk2YWE1ZDY",
    full_address:
      "1724 Mandela Pkwy #6, Oakland, California 94607, United States",
    maki: "marker",
    distance: 12135,
  },
  {
    name: "Sacramento Market",
    mapbox_id:
      "dXJuOm1ieHBvaTpiMWNlYjRlMy01NWYzLTQwMGEtODJlOC0zYTE0NmZhODQwNzQ",
    full_address:
      "2974 Sacramento St, Berkeley, California 94702, United States",
    maki: "grocery",
    distance: 15102,
  },
  {
    name: "Bay Area - Sacramento Realtor",
    mapbox_id:
      "dXJuOm1ieHBvaTo3ZWMzOWIxZS01MTJjLTQwNmYtOWRjNy1lNjkyMjRjYjkzNmU",
    full_address:
      "32250 Devonshire St, Union City, California 94587, United States",
    maki: "marker",
    distance: 37255,
  },
  {
    name: "Sacramento Mailbox",
    mapbox_id:
      "dXJuOm1ieHBvaTozNTYyYjYzYi1kNTcwLTQzMDMtYWRmYS1mOTc2Mzg4YWEyZjU",
    full_address:
      "2991 Sacramento St, Berkeley, California 94703, United States",
    maki: "post",
    distance: 15121,
  },
];
